# Import Function

In [1]:
import pandas as pd

# Dataframe making

In [2]:
# df_original
df = pd.read_csv("Life_expentance.csv") 
# df --> List
Row_list =[]   
head_list = ['Place','Year','Sex','Race','Life expectancy']
for index, rows in df.iterrows(): 
    my_list =[rows.Place, rows.Year, rows.Sex, rows.Race, rows.Value] 
    Row_list.append(my_list)

In [3]:
df = pd.read_csv("All_type_of_cancer.csv") 
list_temp = []
for index, rows in df.iterrows(): 
    my_list =[rows.Place, rows.Year, rows.Sex, rows.Race, rows.Value] 
    list_temp.append(my_list) 
head_list.insert(5,'Cancer')
for i in range(len(Row_list)):
    Row_list[i].insert(5,'NaN')

for i in range(len(Row_list)):
    for j in range(len(list_temp)):
        if list_temp[j][0] ==  Row_list[i][0]:
            if list_temp[j][1] ==  Row_list[i][1]:
                if list_temp[j][2] ==  Row_list[i][2]:
                    if list_temp[j][3] ==  Row_list[i][3]:
                        Row_list[i][5] = list_temp[j][4]
                        break                        

df = pd.read_csv("HIV_AIDS_Rate.csv") 
list_temp = []
for index, rows in df.iterrows(): 
    my_list =[rows.Place, rows.Year, rows.Sex, rows.Race, rows.Value] 
    list_temp.append(my_list) 
head_list.insert(5,'HIV')
for i in range(len(Row_list)):
    Row_list[i].insert(5,'NaN')

for i in range(len(Row_list)):
    for j in range(len(list_temp)):
        if list_temp[j][0] ==  Row_list[i][0]:
            if list_temp[j][1] ==  Row_list[i][1]:
                if list_temp[j][2] ==  Row_list[i][2]:
                    if list_temp[j][3] ==  Row_list[i][3]:
                        Row_list[i][5] = list_temp[j][4]
                        break 

df = pd.read_csv("Diabetes.csv") 
list_temp = []
for index, rows in df.iterrows(): 
    my_list =[rows.Place, rows.Year, rows.Sex, rows.Race, rows.Value] 
    list_temp.append(my_list) 
head_list.insert(5,'Diabetes')
for i in range(len(Row_list)):
    Row_list[i].insert(5,'NaN')

for i in range(len(Row_list)):
    for j in range(len(list_temp)):
        if list_temp[j][0] ==  Row_list[i][0]:
            if list_temp[j][1] ==  Row_list[i][1]:
                if list_temp[j][2] ==  Row_list[i][2]:
                    if list_temp[j][3] ==  Row_list[i][3]:
                        Row_list[i][5] = list_temp[j][4]
                        break                        
#Heart_Disease
df = pd.read_csv("Heart_Disease.csv") 
list_temp = []
for index, rows in df.iterrows(): 
    my_list =[rows.Place, rows.Year, rows.Sex, rows.Race, rows.Value] 
    list_temp.append(my_list) 
head_list.insert(5,'Heart Disease')
for i in range(len(Row_list)):
    Row_list[i].insert(5,'NaN')

for i in range(len(Row_list)):
    for j in range(len(list_temp)):
        if list_temp[j][0] ==  Row_list[i][0]:
            if list_temp[j][1] ==  Row_list[i][1]:
                if list_temp[j][2] ==  Row_list[i][2]:
                    if list_temp[j][3] ==  Row_list[i][3]:
                        Row_list[i][5] = list_temp[j][4]
                        break    

#Vehicle
df = pd.read_csv("Vehicle.csv") 
list_temp = []
for index, rows in df.iterrows(): 
    my_list =[rows.Place, rows.Year, rows.Sex, rows.Race, rows.Value] 
    list_temp.append(my_list) 
head_list.insert(5,'Vehicle')
for i in range(len(Row_list)):
    Row_list[i].insert(5,'NaN')

for i in range(len(Row_list)):
    for j in range(len(list_temp)):
        if list_temp[j][0] ==  Row_list[i][0]:
            if list_temp[j][1] ==  Row_list[i][1]:
                if list_temp[j][2] ==  Row_list[i][2]:
                    if list_temp[j][3] ==  Row_list[i][3]:
                        Row_list[i][5] = list_temp[j][4]
                        break    
#Firearm
df = pd.read_csv("Firearm.csv") 
list_temp = []
for index, rows in df.iterrows(): 
    my_list =[rows.Place, rows.Year, rows.Sex, rows.Race, rows.Value] 
    list_temp.append(my_list) 
head_list.insert(5,'Firearm')
for i in range(len(Row_list)):
    Row_list[i].insert(5,'NaN')

for i in range(len(Row_list)):
    for j in range(len(list_temp)):
        if list_temp[j][0] ==  Row_list[i][0]:
            if list_temp[j][1] ==  Row_list[i][1]:
                if list_temp[j][2] ==  Row_list[i][2]:
                    if list_temp[j][3] ==  Row_list[i][3]:
                        Row_list[i][5] = list_temp[j][4]
                        break    
#Pneumonia_and_Influenza_Mortality_Rate
df = pd.read_csv("Pneumonia_and_Influenza_Mortality_Rate.csv") 
list_temp = []
for index, rows in df.iterrows(): 
    my_list =[rows.Place, rows.Year, rows.Sex, rows.Race, rows.Value] 
    list_temp.append(my_list) 
head_list.insert(5,'Pneumonia and Influenza')
for i in range(len(Row_list)):
    Row_list[i].insert(5,'NaN')

for i in range(len(Row_list)):
    for j in range(len(list_temp)):
        if list_temp[j][0] ==  Row_list[i][0]:
            if list_temp[j][1] ==  Row_list[i][1]:
                if list_temp[j][2] ==  Row_list[i][2]:
                    if list_temp[j][3] ==  Row_list[i][3]:
                        Row_list[i][5] = list_temp[j][4]
                        break

In [4]:
df = pd.DataFrame(Row_list, columns = head_list) 
df

,Place,Year,Sex,Race,Life expectancy,Pneumonia and Influenza,Firearm,Vehicle,Heart Disease,Diabetes,HIV,Cancer
0,"Baltimore, MD",2013,Both,All,73.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Boston, MA",2012,Both,All,80.1,18.3,4.4,5,131.8,19.6,879.3,187.3
2,"Boston, MA",2012,Both,Asian/PI,87.2,NaN,NaN,NaN,45,NaN,NaN,132.4
3,"Boston, MA",2012,Both,Black,77.0,NaN,13.7,NaN,156.2,39.6,1585.2,209.9
4,"Boston, MA",2012,Both,Hispanic,86.4,NaN,NaN,NaN,80.9,NaN,899.5,135.7
...,...,...,...,...,...,...,...,...,...,...,...,...
475,"Washington, DC",2010,Both,Hispanic,88.4,16.6,4.2,2,129.4,19.7,NaN,120.4
476,"Washington, DC",2010,Both,Black,72.8,15.1,26,10,280.9,36.1,NaN,211
477,"Washington, DC",2010,Both,All,77.5,13.4,14,5.6,219.5,24.7,NaN,176.1
478,"Washington, DC",2010,Male,All,74.9,16.6,27.6,7.6,271.7,26.4,NaN,211.5
479,"Washington, DC",2010,Female,All,79.8,11.7,2.1,3.7,183.1,23.7,NaN,156.6